from dotenv import load_dotenv

load_dotenv()

import getpass
import json
import os
import random
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

from google import genai
from google.genai import types

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from mcp_server.security import login_and_get_token
import mcp_server.security as security_mod


def _load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def _save_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _mask_phone(phone: Any) -> str:
    """
    Mask all digits except the last 4.
    Example style: ***-***-4833
    """
    digits = "".join(ch for ch in str(phone) if ch.isdigit())
    if not digits:
        return "********"
    last4 = digits[-4:]
    if len(digits) >= 10:
        return f"***-***-{last4}"
    if len(digits) > 4:
        return f"{'*' * (len(digits) - 4)}-{last4}"
    return last4


def build_gemini_schema(original_schema: dict[str, Any]) -> dict[str, Any]:
    """
    Explicitly builds a clean, token-free Gemini schema from FastMCP parameters.
    Bypasses recursive Pydantic artifacts completely.

    This is intentionally non-recursive: it only translates the top-level
    parameter properties generated by FastMCP/Pydantic.
    """
    gemini_schema: dict[str, Any] = {"type": "OBJECT", "properties": {}}

    properties = original_schema.get("properties") or {}
    for param_name, param_details in properties.items():
        if param_name == "token":
            continue  # silently strip security token from the schema

        # FastMCP/Pydantic typically emits lowercase JSON schema types.
        raw_type = str(param_details.get("type", "string")).strip().lower()
        if raw_type in {"integer"}:
            param_type = "INTEGER"
        elif raw_type in {"number", "float", "double"}:
            param_type = "NUMBER"
        elif raw_type in {"boolean", "bool"}:
            param_type = "BOOLEAN"
        elif raw_type in {"object"}:
            param_type = "OBJECT"
        elif raw_type in {"array"}:
            param_type = "ARRAY"
        else:
            # string, etc.
            param_type = raw_type.upper()

        # We only keep schema keys Gemini accepts; everything else is dropped.
        gemini_schema["properties"][param_name] = {
            "type": param_type,
        }
        desc = param_details.get("description")
        if isinstance(desc, str) and desc.strip():
            gemini_schema["properties"][param_name]["description"] = desc.strip()

    required = original_schema.get("required") or []
    if isinstance(required, list):
        reqs = [r for r in required if r != "token"]
        if reqs:
            gemini_schema["required"] = reqs

    return gemini_schema


def _extract_tools_from_fastmcp(mcp_obj: Any) -> tuple[list[dict[str, Any]], dict[str, Callable[..., Any]]]:
    """
    Extract tool schemas and callables from FastMCP's internal ToolManager registry.
    """
    tool_manager = getattr(mcp_obj, "_tool_manager", None)
    tools_dict = getattr(tool_manager, "_tools", None) if tool_manager is not None else None
    if not isinstance(tools_dict, dict) or not tools_dict:
        return [], {}

    tools: list[dict[str, Any]] = []
    tool_name_to_function: dict[str, Callable[..., Any]] = {}

    for name in sorted(tools_dict.keys()):
        tool = tools_dict[name]
        fn = getattr(tool, "fn", None)
        params = getattr(tool, "parameters", None)
        desc = getattr(tool, "description", "") or ""

        if not callable(fn):
            continue
        if not isinstance(params, dict):
            params = {"type": "object", "properties": {}}

        safe_schema = build_gemini_schema(params)

        tools.append(
            {
                "name": getattr(tool, "name", name),
                "description": desc.strip() or f"Call `{name}`",
                "parameters": safe_schema,
            }
        )
        tool_name_to_function[name] = fn

    return tools, tool_name_to_function


def main() -> None:
    # -----------------------------
    # Step 1: Identity & Simulated MFA
    # -----------------------------
    hris_path = ROOT / "data" / "mock_hris_db.json"
    if not hris_path.exists():
        print(f"Security error: Missing HRIS DB at {hris_path}")
        raise SystemExit(1)

    hris = _load_json(hris_path, default={"meta": {}, "employees": []})
    employees = hris.get("employees") or []

    email = input("Email: ").strip()
    email_key = email.lower()

    profile = next((e for e in employees if str(e.get("email", "")).lower() == email_key), None)
    if not profile:
        print("SECURITY ERROR: No employee record found for that email.")
        raise SystemExit(1)

    employee_name = profile.get("preferred_name") or profile.get("full_name") or ""
    job_title = profile.get("job_title") or ""
    phone = profile.get("phone")
    masked_phone = _mask_phone(phone)

    print(f"[SYSTEM: Sending SMS OTP to {masked_phone}...]")
    otp = random.randint(100000, 999999)
    time.sleep(2)
    print(f"[SIMULATED PHONE: You received a message: \"Your ExampleCorp OTP is {otp}\"]")

    otp_input = input("Enter OTP: ").strip()
    if otp_input != str(otp):
        print("Security error: Incorrect OTP. Access denied.")
        raise SystemExit(1)

    # -----------------------------
    # Step 2: Account Claim (Password Setup)
    # -----------------------------
    password = getpass.getpass("Create a new password: ")
    auth_path = ROOT / "data" / "auth_db.json"
    auth_db = _load_json(auth_path, default={"users": {}})
    auth_db.setdefault("users", {})

    # Prefer security_mod.hash_password. If it doesn't exist in this repo version,
    # define it at runtime so we still use the requested API name.
    if not hasattr(security_mod, "hash_password") or not callable(getattr(security_mod, "hash_password")):
        from werkzeug.security import generate_password_hash

        def _hash_password(pw: str) -> str:
            return generate_password_hash(pw)

        security_mod.hash_password = _hash_password  # type: ignore[attr-defined]

    password_hash = security_mod.hash_password(password)  # type: ignore[attr-defined]

    auth_db["users"][email_key] = {
        "email": email_key,
        "password_hash": password_hash,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    _save_json(auth_path, auth_db)

    # -----------------------------
    # Step 3: Document Verification (Gemini Vision)
    # -----------------------------
    file_path = input("Enter the file path to your Offer Letter (e.g., paul_offer.txt): ").strip()
    if not file_path:
        print("Security error: Offer letter file path is required.")
        raise SystemExit(1)

    file_abs = Path(file_path)
    if not file_abs.exists():
        print(f"Security error: File not found: {file_abs}")
        raise SystemExit(1)

    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if not gemini_api_key:
        print("Missing GEMINI_API_KEY. Add it to your environment or `.env`.")
        raise SystemExit(1)

    client = genai.Client(api_key=gemini_api_key,http_options={'api_version': 'v1beta'})

    uploaded = client.files.upload(file=str(file_abs))
    verification_prompt = (
        f"Read this offer letter. Does the name and job title match the database record for "
        f"{employee_name} as a {job_title}? Reply with a brief welcome message if it matches, "
        f"or a security warning if it does not."
    )

    verification = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[verification_prompt, uploaded],
    )
    if getattr(verification, "text", None):
        print("\nGemini verification result:\n" + (verification.text or "").strip() + "\n")

    # -----------------------------
    # Step 4: The Chat Handoff (JWT + tool calling)
    # -----------------------------
    jwt_token = login_and_get_token(email=email, password=password)

    from mcp_server import server as mcp_server_module

    tools, tool_name_to_function = _extract_tools_from_fastmcp(mcp_server_module.mcp)
    if len(tools) != 20:
        raise RuntimeError(f"Expected 20 tools, found {len(tools)}.")

    system_prompt = (
        "You are an Enterprise HR & IT Orchestration Agent operating in a secure environment. "
        "You strictly adhere to Role-Based Access Control (RBAC) enforced by the backend server. "
        
        "### CORE RULES FOR DATA ACCESS:\n"
        "1. Employees may access their own personal HR and IT data.\n"
        "2. Managers are authorized to view data ONLY for their direct reports (based on manager_employee_id).\n"
        "3. HR personnel (People Ops, Human Resources, Executive) have elevated clearance to view data for any employee.\n"
        
        "### CRITICAL WORKFLOW - NAME TO ID LOOKUP:\n"
        "- If a user asks about an employee by name (e.g., 'Paul Turner'), you MUST first call the `get_coworker_contact` tool with that name.\n"
        "- From the results, extract the 'employee_id' (e.g., 'E1049').\n"
        "- Use that 'employee_id' as the 'target_employee_id' parameter in subsequent tool calls (Salary, PTO, Equipment, Performance).\n"
        
        "### ERROR HANDLING:\n"
        "- Do not pre-emptively block requests. Always execute the tool; the backend will verify authorization via the JWT token.\n"
        "- If the server returns an 'ACCESS DENIED' error, politely inform the user they lack the required HR or Manager clearance for that specific record."
    )
    
    # Injects the dynamic session context so the AI knows who it is representing
    system_prompt += f"\n\nCURRENT USER SESSION: You are currently assisting the user logged in as: {email}."

    function_declarations: list[types.FunctionDeclaration] = []
    for t in tools:
        function_declarations.append(
            types.FunctionDeclaration(
                name=t["name"],
                description=t.get("description", ""),
                parameters=t.get("parameters"),
            )
        )
    tool_obj = types.Tool(function_declarations=function_declarations)

    chat = client.chats.create(
        model="gemini-2.5-flash",
        config=types.GenerateContentConfig(
            system_instruction=system_prompt,
            tools=[tool_obj],
        ),
    )

    print("Onboarding complete. Secure chat is ready.")
    print("Type your message. Use `/exit` to quit.\n")

    while True:
        user_text = input("> ").strip()
        if not user_text:
            continue
        if user_text.lower() in {"/exit", "exit", "quit"}:
            break

        response = chat.send_message(user_text)

        while getattr(response, "function_calls", None):
            for call in response.function_calls:
                fn_name = call.name
                fn_args = dict(call.args or {})
                fn_args["token"] = jwt_token

                fn = tool_name_to_function.get(fn_name)
                if fn is None:
                    function_response = {"error": f"Unknown tool: {fn_name}"}
                else:
                    try:
                        result = fn(**fn_args)
                        function_response = {"result": result}
                    except Exception as e:
                        function_response = {"error": f"{type(e).__name__}: {e}"}

                function_response_part = types.Part.from_function_response(
                    name=fn_name,
                    response=function_response,
                )
                response = chat.send_message(function_response_part)

        if getattr(response, "text", None):
            print((response.text or "").strip() + "\n")


if __name__ == "__main__":
    main()

